### ISSUE TITLE
[APP SUBMITTED]: Thread-15 :: [5bc5c3a] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by Hisha** [Sick-Rage/Sick-Rage#4275] opened 2018-01-27 14:40 UTC
### INFO
Python Version: **2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]**
Operating System: **Linux-4.9.76-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [5bc5c3a] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by randmvilnce** [comment] 2018-01-29 21:16
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
Thread-1649 :: [5bc5c3a] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bigjoe888** [comment] 2018-01-30 12:31
Same issue here, found a post suggesting to delete the cache.db file, but the error came back after a few minutes. Not sure if related to this , but also experiencing timeouts with thetvdb.com when adding new tv shows

**Comment by gmccauley** [comment] 2018-02-03 22:51
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [5bc5c3a] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by tahirzia** [comment] 2018-02-04 16:31
### INFO
Python Version: **2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
Thread-2840 :: [5bc5c3a] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Tiwas** [comment] 2018-02-06 01:24
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
TORNADO :: [5bc5c3a] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by blakadder** [comment] 2018-02-06 17:51
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [5bc5c3a] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by djoole** [comment] 2018-02-06 21:26
Dup of #4257

**Comment by WebSpider** [comment] 2018-03-23 13:34
Duplicate of #4257

**Closed** 2018-10-10 06:57 UTC
