### ISSUE TITLE
[APP SUBMITTED]: Thread-16 :: [5066fab] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by m184711** [Sick-Rage/Sick-Rage#4321] opened 2018-02-19 07:31 UTC
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [5066fab] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by statik1983** [comment] 2018-02-19 10:49
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [5066fab] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sossienl** [comment] 2018-02-20 08:15
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [5066fab] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-03-23 13:35
Duplicate of #4257

**Closed** 2018-10-10 06:57 UTC
