### ISSUE TITLE
[APP SUBMITTED]: Thread-14 :: [f30a844] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by Eakster** [Sick-Rage/Sick-Rage#4300] opened 2018-02-07 06:41 UTC
### INFO
Python Version: **2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]**
Operating System: **Darwin-16.7.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [f30a844] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by XxUnkn0wnxX** [comment] 2018-02-09 17:14
### INFO
Python Version: **2.7.14 (default, Jan  6 2018, 01:55:26) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]**
Operating System: **Darwin-17.4.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
MANUAL :: [f30a844] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by m184711** [comment] 2018-02-15 05:39
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [f30a844] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-03-23 13:35
Duplicate of #4257

**Closed** 2018-10-10 06:57 UTC
