### ISSUE TITLE
[APP SUBMITTED]: TORNADO :: [6e3a1dc] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by MotleyC** [Sick-Rage/Sick-Rage#4341] opened 2018-02-28 20:47 UTC
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@6e3a1dccd94857fc381c9a246b903904eca424e1
No Log available with ERRORS:
### ERROR
```
TORNADO :: [6e3a1dc] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by trdemoss** [comment] 2018-03-02 18:52
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e3a1dccd94857fc381c9a246b903904eca424e1
No Log available with ERRORS:
### ERROR
```
Thread-691 :: [6e3a1dc] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sulaiman-allen** [comment] 2018-03-05 14:55
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6e3a1dccd94857fc381c9a246b903904eca424e1
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [6e3a1dc] Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-03-23 13:35
Duplicate of #4257

**Closed** 2018-10-10 06:57 UTC
