### ISSUE TITLE
[APP SUBMITTED]: Thread-23 :: [53e6cc5] Missing time zone for network: Slash. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by sulaiman-allen** [Sick-Rage/Sick-Rage#4382] opened 2018-03-12 23:28 UTC
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@53e6cc50c086757c31fc518b550d7681c61649e6
No Log available with ERRORS:
### ERROR
```
Thread-23 :: [53e6cc5] Missing time zone for network: Slash. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-03-23 13:33
Duplicate of #4349

**Closed** 2018-10-10 06:56 UTC
